services:
  strtchy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strtchy
    restart: unless-stopped
    ports:
      - "4173:4173"
    volumes:
      - ./data:/app/data
    env_file:
      - .env.production
    environment:
      - DATABASE_URL=/app/data/prod/local.db # Ruta absoluta corregida (sin el punto)
      - PORT=4173
      - HOST=0.0.0.0
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=host
    working_dir: /app
